# -*- coding: utf-8 -*-
"""resume_guider.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_JTSeXs0u-6xOAxgCaV5uodorR-Jr_A
"""

# pip install PyPDF2 langchain langchain_groq

# llm setup

from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq


groq_api_key = input("Enter Your Grow API Key.")

llm = ChatGroq(
        temperature=0.7,
        groq_api_key=groq_api_key,
        model_name="llama-3.1-70b-versatile"
).with_structured_output(dict,method="json_mode")

prompt_template = PromptTemplate.from_template(
"""
Hey Act Like a skilled or very experience ATS(Application Tracking System)
with a deep understanding of tech field,software engineering,data science ,data analyst
and big data engineer. Your task is to evaluate the resume based on the given job description.
You must consider the job market is very competitive and you should provide
best assistance for improving the resumes. Assign the percentage Matching based
on Job Description and
the missing keywords with high accuracy
resume:{text}
description:{jd}

I want the response in one single string having the JSON structure
{{"Job_Description_Match":"%","MissingKeywords:[]","Resume Summary":""}}
"""
)
chain = prompt_template | llm

import PyPDF2 as pdf

def input_pdf_text(uploaded_file):
    reader=pdf.PdfReader(uploaded_file)
    text=""
    for page in range(len(reader.pages)):
        page=reader.pages[page]
        text+=str(page.extract_text())
    return text

def get_file_path(uploaded_file):
  for filename in uploaded_file.keys():
      file_path = "/content/" + filename
      return file_path

from google.colab import files

# Step 1: Allow the user to upload a PDF file
uploaded_file = files.upload()

file_path = get_file_path(uploaded_file)

def guider(text,jd):
    result = chain.invoke({'text': text,'jd':jd})
    return result

job_description = input("Enter the Job Description : ");

pdf_text = input_pdf_text(file_path)

response = guider(pdf_text,job_description)

print(f"Job Description match: {response['Job_Description_Match']}")
print(f"Missing Keywords: {', '.join(response['MissingKeywords'])}")
print(f"Resume Summary: {response['Resume Summary']}")